name: Deploy to Instance

env:
    REPO_NAME: ${{ github.event.repository.name }}
    REPO_URL: ${{ github.event.repository.url }}

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Connect to AWS Lightsail, extract file and delete the file
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.HOST_IP }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  passphrase: ""
                  port: 22
                  script: |
                      # Create the directory with sudo
                      sudo mkdir -p /var/www/AsisRetail

                      # Change ownership of the directory to your user
                      sudo chown -R $USER:$USER /var/www/AsisRetail

                      # Initialize the directory as a Git repository if it's not already
                      if [ ! -d /var/www/AsisRetail/.git ]; then
                        cd /var/www/AsisRetail
                        git init
                      fi

                      # Perform Git pull with the specified branch
                      cd /var/www/AsisRetail
                      git pull origin main

                      # Check if directories exist before changing into them
                      if [ -d Frontend ]; then
                        cd Frontend
                        sudo npm install
                        sudo npm run build
                      else
                        echo "Frontend directory does not exist."
                      fi

                      if [ -d Admin ]; then
                        cd ../Admin
                        sudo npm install
                        sudo npm run build
                      else
                        echo "Admin directory does not exist."
                      fi

                      if [ -d Backend ]; then
                        cd ../Backend
                        sudo npm install
                        if sudo npm stop; then
                          echo "Command 1 succeeded"
                          sudo npm start
                        else
                          echo "Command 1 failed"
                          sudo npm start
                        fi
                      else
                        echo "Backend directory does not exist."
                      fi
